### ISSUE TITLE
runProguard()がない？

### ISSUE THREAD

**Issue by AmaneShiki** [mixi-inc/AndroidTraining#48]
いつもお世話になっております。
既出の問題でしたら申し訳ございません。

AndroidTrainingのfundamentalsプロジェクトをベースに以下の変更を行い、
プロジェクトをインポートしたところ、
`runProguard`の設定でエラーになりました。

変更内容:
gradle: 0.8.+→1.0.0
compileSdkVersion: 17→21
buildToolsVersion: 21.0.2→21.1.2
AndroidStudio: 1.0.2 

[AndroidStudioのバージョンが1.0以降はminifyEnabledを使用してください](http://stackoverflow.com/questions/27233800/android-studio-could-not-find-method-runproguard-for-arguments)とのことらしいので
手動でぽちぽち直しているのですが、
該当箇所の修正をプロジェクトにも取り込んでいただけると有難いです。
お手数おかけいたしますが、よろしくお願い致します。

**Comment by hidey** [comment]
ご指摘ありがとうございます
修正します

**Comment by hidey** [comment]
@AmaneShiki 
対応しました

**Comment by AmaneShiki** [comment]
@hidey 
ご対応ありがとうございます。
