### ISSUE TITLE
第1回の準備

### ISSUE THREAD

**Issue by punchdrunker** [mixi-inc/AndroidTraining#56]
### 補足

gitter投下用なのであえてmarkdownせず

* ASのよく使うショートカット
 * Android Studio ショートカットキーリスト for Mac http://qiita.com/Tazake/items/5c725a8b68d13271d43d
 * Android Studioで覚えておくと便利なこと http://qiita.com/sugoi_wada/items/db449d5cbb5c83cb586c
 * 変更したい人は  Android StudioにEclipseのショートカットを効かせる http://qiita.com/tomoima525/items/59d3a266c4528290ddc9
 * Ctrl+Spaceでspotlightが開いちゃう人はASかSpotliteのショートカットを変えた方が良いかも
* 調べものはなるべく本家で
 * Package Index | Android Developers https://developer.android.com/reference
* XMLの名前空間宣言については軽くリンク共有 (知らないとScrollViewPractice/Practice1でハマるかも)
 * XML名前空間の簡単な説明 http://www.kanzaki.com/docs/sw/names.html
* 実習のヒント
 * RelativeLayoutPractice/Practice2はLinearLayout使っても大丈夫
 * ScrollViewPractice/Practice1はスクロール領域の中にボタンを置くこと
* layout_weightのネストが重い話について軽く記事の紹介だけでも
 * Qiita - Viewのネストはどのくらい遅いのか ー 12階層のレイアウトを5階層にして検証してみた http://qiita.com/konifar/items/3c75f1fab0e0a10ebb14

### DONE:

* レイアウトについての章を学習するにあたっての、手順とかファイル名の追記
 * どういうプロジェクトを作って、そもそもレイアウトファイルどこにあるとか
* エミュレータについての注意事項
 * 詳細は書かないが、x86とかgenymotionとかあるけど、一番簡単なのは実機使う、みたいな事をconnpassとかに書いておく

**Comment by hidey** [comment]
第1回は終わっているのでdone
